---
pg_repo_el6: "http://yum.postgresql.org/{{ pg_version }}/redhat/rhel-6-x86_64/pgdg-redhat{{ pg_version_nodot }}-{{ pg_version }}-1.noarch.rpm"
pg_repo_el7: "http://yum.postgresql.org/{{ pg_version }}/redhat/rhel-7-x86_64/pgdg-centos{{ pg_version_nodot }}-{{ pg_version }}-3.noarch.rpm"

pg_packages:
  - "postgresql{{ pg_version_nodot }}"
  - "postgresql{{ pg_version_nodot }}-libs"
  - "postgresql{{ pg_version_nodot }}-server"
  - "postgresql{{ pg_version_nodot }}-contrib"
  #- "python-psycopg2"  (revert after migration to python3)
  # compiled for pg95:
  - "https://download.erigones.org/rpm/python-psycopg2-dc-2.7.5-1.el7.x86_64.rpm"

pg_datadir: "/var/lib/pgsql/{{ pg_version }}/data/"
pg_backupdir: "/var/lib/pgsql/{{ pg_version }}/backups"
pg_service: "postgresql-{{ pg_version }}"
